spring:
    # jdbc_config   datasource
    datasource:
      url: jdbc:p6spy:mysql://39.97.225.44:3306/ry?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      hikari:
        username: java_usr
        password: javaUsrPassword@7
        minimum-idle: 8
        maximum-pool-size: 20
        max-lifetime: 1800000
        connection-timeout: 30000
mybatis-plus:
    check-config-location: true
    #sql log
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
